version: "3.9"

services:
  php54:
    container_name: php54
    build: "./"
    networks:
      - default
    volumes:
      - '${WEBROOT}:/webroot'
    ports:
      - '${PHP_FPM_PORT}:9000'
    restart: unless-stopped
networks:
  default:
    external: true
    name: ${NETWORK_NAME}
