version: "3.9"

services:
  mysql57:
    container_name: mysql57
    build: "./"
    networks:
      - default
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
    restart: unless-stopped
networks:
  default:
    external: true
    name: ${NETWORK_NAME}
