version: "3.9"

services:
  dnsmasq:
    container_name: dnsmasq
    build: "./"
    ports:
      - '53:53/udp'
    networks:
      - default
    restart: unless-stopped
networks:
  default:
    external: true
    name: ${NETWORK_NAME}
