version: "3.9"

services:
  mariadb106:
    container_name: mariadb106
    build: "./"
    networks:
      - default
    ports:
      - '${MARIADB_PORT}:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    restart: unless-stopped
networks:
  default:
    external: true
    name: ${NETWORK_NAME}
