version: "3.9"

services:
  nginx:
    container_name: nginx
    build: "./"
    networks:
      - default
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${WEBROOT}:/webroot:ro
    restart: unless-stopped
networks:
  default:
    external: true
    name: ${NETWORK_NAME}
