version: "3.9"

services:
  ruby30:
    container_name: ruby30
    build: "./"
    networks:
      - default
    volumes:
      - ./data:/data
    restart: unless-stopped
networks:
  default:
    external: true
    name: ${NETWORK_NAME}
