version: "3.9"

services:
  elasticsearch7142:
    container_name: elasticsearch7142
    build: "./"
    networks:
      - default
    ports:
      - '${ELASTICSEARCH_PORT_REQUEST}:9200'
      - '${ELASTICSEARCH_PORT_COMM}:9300'
    volumes:
      - ./data/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    restart: unless-stopped
networks:
  default:
    external: true
    name: ${NETWORK_NAME}
